/// The [[7,1,3]] Steane code and the pieces of the rotation protocol: encoder, transversal
/// rotation, dephasing (two implementations), X-type syndrome extraction (Steane block or
/// joint measurements), the decoder, and transversal logical readout.
///
/// Qubit j of the data register is column j + 1 of the Hamming parity-check matrix
///   H = [[0,0,0,1,1,1,1],
///        [0,1,1,0,0,1,1],
///        [1,0,1,0,1,0,1]]     (Eq. 1 of arXiv:2608.20676),
/// so the X-syndrome of a Z error on qubit j, read as the binary number s1 s2 s3, is j + 1.
import Std.Math.ArcSin;
import Std.Math.Sqrt;
import Std.Measurement.MResetEachZ;
import Std.Random.DrawRandomBool;

/// Supports of the three rows of H: the X-type and Z-type stabilizer generators.
function Rows() : Int[][] {
    [[3, 4, 5, 6], [1, 2, 5, 6], [0, 2, 4, 6]]
}

/// |0_L>: the uniform superposition of the 8 strings generated by the rows of H. Each row has
/// a pivot qubit (3, 1, 0) that no other row touches: H on the pivots, CNOTs along the rows.
operation EncodeZero(qs : Qubit[]) : Unit is Adj {
    H(qs[0]);
    H(qs[1]);
    H(qs[3]);
    CNOT(qs[0], qs[2]);
    CNOT(qs[0], qs[4]);
    CNOT(qs[0], qs[6]);
    CNOT(qs[1], qs[2]);
    CNOT(qs[1], qs[5]);
    CNOT(qs[1], qs[6]);
    CNOT(qs[3], qs[4]);
    CNOT(qs[3], qs[5]);
    CNOT(qs[3], qs[6]);
}

/// Logical inputs from transversal Cliffords: 0 = |0_L>, 1 = |1_L> = X^7 |0_L>,
/// 2 = |+_L> = H^7 |0_L>, 3 = |+i_L> = S_L |+_L>. On the code space S_L is (S^dagger)^7,
/// because the strings of |1_L> have weight 3 or 7 and (-i)^3 = (-i)^7 = i.
operation PrepareLogical(input : Int, qs : Qubit[]) : Unit {
    EncodeZero(qs);
    if input == 1 {
        for q in qs { X(q); }
    }
    if input == 2 or input == 3 {
        for q in qs { H(q); }
    }
    if input == 3 {
        for q in qs { Adjoint S(q); }
    }
}

/// Transversal Rz(theta) = exp(-i theta Z / 2) on every qubit.
operation Rotate(theta : Double, qs : Qubit[]) : Unit {
    for q in qs { Rz(theta, q); }
}

/// Dephasing of strength p on every qubit, D_p(rho) = (1 - p) rho + p Z rho Z, as a
/// Stinespring dilation onto a fresh environment qubit each:
///   |psi>|0>_E -> sqrt(1 - p) |psi>|0>_E + sqrt(p) Z|psi> |1>_E.
/// Exact and dumpable; Python traces the environment out.
operation DephaseDilated(p : Double, qs : Qubit[], env : Qubit[]) : Unit {
    for i in 0..Length(qs) - 1 {
        Ry(2.0 * ArcSin(Sqrt(p)), env[i]);
        CZ(env[i], qs[i]);
    }
}

/// The same channel for shots: the dilation with its environment measured right away, so
/// each qubit gets a Z flip with probability p and the state stays sparse. The flip is drawn
/// by the simulator's measurement rather than by DrawRandomBool: under a fixed seed the QDK
/// seeds its classical random numbers and its measurement outcomes identically, so the k-th
/// classical draw of a shot uses the same number as its k-th measurement, which correlates
/// sampled flips with the syndromes measured afterwards (verify.py shows it).
operation DephaseSampled(p : Double, qs : Qubit[]) : Unit {
    use env = Qubit[Length(qs)];
    DephaseDilated(p, qs, env);
    MResetEachZ(env);
}

/// The naive version, kept only for that check.
operation DephaseDrawn(p : Double, qs : Qubit[]) : Unit {
    for q in qs {
        if DrawRandomBool(p) { Z(q); }
    }
}

/// H x: the parity of a measured 7-bit string over each row of H, as three Results.
function Syndrome(x : Result[]) : Result[] {
    mutable s = [];
    for row in Rows() {
        mutable ones = 0;
        for j in row {
            if x[j] == One { ones += 1; }
        }
        s += [ones % 2 == 1 ? One | Zero];
    }
    s
}

/// Steane extraction of the X-type generators (Fig. 3 of the paper): an ancilla block in
/// |0_L>, transversal CNOT from the ancilla onto the data, ancilla read out in the X basis.
/// The ancilla string x is a random Hamming code word shifted by the data's Z errors, so
/// H x is the data's X-syndrome; the data register is projected onto that syndrome's
/// sector and not otherwise disturbed.
operation MeasureXSyndrome(qs : Qubit[]) : Result[] {
    use anc = Qubit[7];
    EncodeZero(anc);
    for i in 0..6 { CNOT(anc[i], qs[i]); }
    for a in anc { H(a); }
    Syndrome(MResetEachZ(anc))
}

/// The same syndrome from three joint X-parity measurements: no ancillas, a simulator
/// convenience used to check the block.
operation MeasureXSyndromeDirect(qs : Qubit[]) : Result[] {
    mutable s = [];
    for row in Rows() {
        s += [Measure([PauliX, PauliX, PauliX, PauliX], [qs[row[0]], qs[row[1]], qs[row[2]], qs[row[3]]])];
    }
    s
}

/// The decoder: the syndrome read as the binary number s1 s2 s3 is the column of H, i.e. the
/// flagged qubit plus one. Returns -1 for the trivial syndrome.
function FlaggedQubit(s : Result[]) : Int {
    (s[0] == One ? 4 | 0) + (s[1] == One ? 2 | 0) + (s[2] == One ? 1 | 0) - 1
}

/// Z on the flagged qubit, nothing for the trivial syndrome.
operation Correct(s : Result[], qs : Qubit[]) : Unit {
    let j = FlaggedQubit(s);
    if j >= 0 { Z(qs[j]); }
}

/// Transversal logical readout in the Z (0), X (1) or Y (2) basis: the Clifford that maps
/// the wanted logical Pauli to Z_L, then every qubit in Z. Y_L = S_L X_L S_L^dagger, and
/// S_L^dagger is S^7 on the code space. Python decodes the 7-bit string (nearest code word,
/// then the parity of its weight).
operation MeasureLogical(basis : Int, qs : Qubit[]) : Result[] {
    if basis == 2 {
        for q in qs { S(q); }
    }
    if basis >= 1 {
        for q in qs { H(q); }
    }
    MResetEachZ(qs)
}
