"""Checks that the Q# circuits implement the code, the rotation, the noise and the syndrome
extraction the paper analyses, that the exact logical channel read off the dumps is what the
closed forms say, and that the shot-based estimators agree with it.

Run with `python verify.py` (~1 min, mostly shots).
"""

from __future__ import annotations

import sys

import numpy as np

import driver
import steane as st

failures: list[str] = []
SEED = 1000


def sd(k: int) -> int:
    """Seeds for the shot runs of this script, one SEED_STRIDE apart so that no two runs share
    random numbers (qsharp.run seeds shot i with seed + i)."""
    return SEED + k * driver.SEED_STRIDE


def check(name: str, ok: bool, detail: str) -> None:
    print(f"  [{'PASS' if ok else 'FAIL'}] {name}: {detail}")
    if not ok:
        failures.append(name)


def info(name: str, detail: str) -> None:
    print(f"  [INFO] {name}: {detail}")


def sigma(est: float, se: float, exact: float) -> float:
    return abs(est - exact) / se if se > 0 else (0.0 if abs(est - exact) < 1e-12 else float("inf"))


def main() -> int:
    driver.init()

    print("\n1. the code and the transversal gates")
    worst = 0.0
    for i, name in enumerate(("|0_L>", "|1_L>", "|+_L>", "|+i_L>")):
        worst = max(worst, abs(abs(np.vdot(st.LOGICAL_INPUTS[i], driver.encoded(i))) - 1))
    check("PrepareLogical matches the numpy code states for all four inputs", worst < 1e-12, f"max |1 - overlap| = {worst:.1e}")
    words = sorted(st.index(w) for w in st.CODEWORDS0)
    support = sorted(int(i) for i in np.flatnonzero(np.abs(driver.encoded(0)) > 1e-9))
    weights = sorted(set(int(st.WEIGHTS[i]) for i in support))
    check("|0_L> is the uniform superposition of the 8 strings generated by the rows of H, weights 0 and 4",
          support == words and weights == [0, 4] and np.allclose(np.abs(driver.encoded(0)[support]), 1 / np.sqrt(8)), f"support {support}, weights {weights}")
    worst = 0.0
    for v in st.LOGICAL_INPUTS.values():
        for P in st.X_STABILIZERS + st.Z_STABILIZERS:
            worst = max(worst, float(np.abs(P @ v - v).max()))
    check("all six stabilizer generators fix the four code states", worst < 1e-12, f"max |S psi - psi| = {worst:.1e}")
    ev = {i: (np.vdot(v, st.X_L @ v).real, np.vdot(v, (1j * st.X_L @ st.Z_L) @ v).real, np.vdot(v, st.Z_L @ v).real) for i, v in st.LOGICAL_INPUTS.items()}
    ok = all(np.allclose(ev[i], st.INPUT_BLOCH[i], atol=1e-12) for i in range(4))
    check("logical Bloch vectors (0,0,1), (0,0,-1), (1,0,0), (0,1,0) under X_L = X^7, Z_L = Z^7, Y_L = i X_L Z_L", ok,
          ", ".join(f"input {i}: ({a:+.3f}, {b:+.3f}, {c:+.3f})" for i, (a, b, c) in ev.items()))
    r = [float(driver.one_round(inp, 0.0, 0.0, basis, 300, sd(k))[1].mean()) for k, (inp, basis) in enumerate(((1, 0), (2, 1), (3, 2), (0, 0)))]
    check("transversal readout decodes: Z on |1_L> = -1, X on |+_L> = +1, Y on |+i_L> = +1, Z on |0_L> = +1 in every shot",
          r == [-1.0, 1.0, 1.0, 1.0], f"means {r}")

    print("\n2. the physical channel")
    worst = worst_mask = 0.0
    for inp, theta, p in ((2, 0.3, 0.0), (3, 0.7, 0.05), (0, 1.1, 0.2), (1, 2.0, 0.5)):
        v = st.LOGICAL_INPUTS[inp]
        rho0 = np.outer(v, v.conj())
        rho = driver.rotated(inp, theta, p)
        worst = max(worst, float(np.abs(rho - st.physical_channel(rho0, theta, p)).max()))
        worst_mask = max(worst_mask, float(np.abs(rho - st.dephasing_mask(theta, p) * rho0).max()))
    check("Rz(theta)^7 plus the dephasing dilation == the Kraus channel of Eq. 2 on the data register", worst < 1e-12, f"max |diff| = {worst:.1e}")
    check("and == the diagonal action of Eq. 11, lambda^{|x xor y|} e^{i theta (|x| - |y|)}", worst_mask < 1e-12, f"max |diff| = {worst_mask:.1e}")
    theta, p, shots = np.pi / 8, 0.02, 20000
    exact_pt = st.exact_channel(theta, p, 0).probability
    sig = {}
    for variant, seed in (("block", sd(4)), ("direct", sd(5))):
        syn, _ = driver.one_round(2, theta, p, 1, shots, seed, variant=variant)
        pt = float((syn == 0).mean())
        sig[variant] = sigma(pt, np.sqrt(exact_pt * (1 - exact_pt) / shots), exact_pt)
    check("sampled dephasing (measured dilation): trivial-syndrome rate within 3 sigma of the exact channel, block and joint measurements",
          max(sig.values()) < 3, f"{sig['block']:.1f} and {sig['direct']:.1f} sigma at theta = pi/8, p = 0.02, {shots} shots")

    print("\n3. syndrome extraction and correction")
    theta, p = np.pi / 8, 0.02
    rows = driver.corrected(2, theta, p, 30, sd(6))
    branches = st.project_data(driver.rotated(2, theta, p))
    worst = worst_leak = 0.0
    seen = set()
    for s, rho in rows:
        seen.add(s)
        ref = branches[s] / np.trace(branches[s]).real
        worst = max(worst, float(np.abs(rho - ref).max()))
        worst_leak = max(worst_leak, abs(st.logical_block(rho)[1]))
    check("the corrected state Q# dumps for a measured syndrome == the projected and corrected branch in numpy",
          worst < 1e-10 and len(seen) >= 3, f"max |diff| = {worst:.1e} over {len(rows)} shots, {len(seen)} distinct syndromes")
    check("after the correction the state is back in the code space", worst_leak < 1e-12, f"max leakage {worst_leak:.1e}")
    probs = {i: [st.branch(st.physical_channel(np.outer(v, v.conj()), 0.4, 0.03), s).trace().real for s in range(8)] for i, v in st.LOGICAL_INPUTS.items()}
    spread = max(float(np.abs(np.array(probs[i]) - np.array(probs[0])).max()) for i in range(1, 4))
    check("the syndrome distribution does not depend on the logical input (theta = 0.4, p = 0.03)", spread < 1e-12,
          f"max spread over the four inputs {spread:.1e}; p_s = {np.round(probs[0], 4).tolist()}")
    chs = [st.exact_channel(0.4, 0.03, s) for s in range(8)]
    nsym = max(float(np.abs(chs[s].matrix - chs[1].matrix).max()) for s in range(2, 8))
    check("all seven nontrivial syndromes give the same logical channel", nsym < 1e-12, f"max spread {nsym:.1e}")

    print("\n4. the ideal channel (p = 0)")
    worst = dict(unit=0.0, cov=0.0, leak=0.0, phi_t=0.0, phi_t_closed=0.0, phi_n=0.0, prob=0.0)
    for theta in np.linspace(0.02, np.pi / 2 - 0.02, 40):
        rot = {i: driver.rotated(i, float(theta), 0.0) for i in range(4)}
        for s in (0, 1):
            ch = st.channel_from_states({i: st.branch(rot[i], s) for i in range(4)})
            worst["unit"] = max(worst["unit"], ch.unitarity_residual())
            worst["cov"] = max(worst["cov"], ch.covariance_residual())
            worst["leak"] = max(worst["leak"], ch.leakage)
            worst["prob"] = max(worst["prob"], abs(ch.probability - st.ideal_prob(theta, s == 0)))
            if s == 0:
                worst["phi_t"] = max(worst["phi_t"], st.angle_diff(ch.angle, st.ideal_angle(theta, True)))
                worst["phi_t_closed"] = max(worst["phi_t_closed"], st.angle_diff(ch.angle, st.trivial_angle_closed(theta)))
            else:
                worst["phi_n"] = max(worst["phi_n"], st.angle_diff(ch.angle, 3 * theta))
    check("every branch is a unitary Z rotation on the code space (|eta| = p_s, populations kept, no leakage)",
          max(worst["unit"], worst["cov"], worst["leak"]) < 1e-12, f"unitarity {worst['unit']:.1e}, covariance {worst['cov']:.1e}, leakage {worst['leak']:.1e}")
    check("p_t = (25 + 7 cos 4 theta) / 32 and p_n = (1 - cos 4 theta) / 32 (Eqs. 20, 21)", worst["prob"] < 1e-12, f"max |diff| = {worst['prob']:.1e}")
    check("phi_t = -arg[e^{i theta} (7 + e^{-4 i theta})^2] (Eq. 22) and the half-angle closed form tan(phi_t/2) = -(7c^4 s^3 + s^7)/(c^7 + 7 c^3 s^4)",
          max(worst["phi_t"], worst["phi_t_closed"]) < 1e-10, f"max |diff| {worst['phi_t']:.1e} (Eq. 22), {worst['phi_t_closed']:.1e} (closed form)")
    check("phi_n = 3 theta (Eq. 23)", worst["phi_n"] < 1e-10, f"max |diff| = {worst['phi_n']:.1e}")
    rot = {i: driver.rotated(i, np.pi / 4, 0.0) for i in range(4)}
    ct, cn = (st.channel_from_states({i: st.branch(rot[i], s) for i in range(4)}) for s in (0, 1))
    check("theta = pi/4: p_t = 9/16, phi_t = -pi/4 and phi_n = 3pi/4, one logical T^dagger up to a heralded Z_L",
          abs(ct.probability - 9 / 16) < 1e-12 and st.angle_diff(ct.angle, -np.pi / 4) < 1e-10 and st.angle_diff(cn.angle, 3 * np.pi / 4) < 1e-10
          and st.angle_diff(cn.angle - ct.angle, np.pi) < 1e-10,
          f"p_t = {ct.probability:.6f}, phi_t = {ct.angle / np.pi:+.6f} pi, phi_n = {cn.angle / np.pi:+.6f} pi")
    rot = {i: driver.rotated(i, np.pi / 2, 0.0) for i in range(4)}
    ct = st.channel_from_states({i: st.branch(rot[i], 0) for i in range(4)})
    check("theta = pi/2: the trivial syndrome is certain and phi_t = -pi/2, the transversal S gate", abs(ct.probability - 1) < 1e-12 and st.angle_diff(ct.angle, -np.pi / 2) < 1e-10,
          f"p_t = {ct.probability:.12f}, phi_t = {ct.angle / np.pi:+.6f} pi")
    ratios = [st.exact_channel(th, 0.0, 0).angle / th**3 for th in (0.02, 0.01, 0.005)]
    check("small angles: phi_t -> -(7/4) theta^3", abs(ratios[-1] + 7 / 4) < 2e-3, f"phi_t / theta^3 = {ratios[0]:.4f}, {ratios[1]:.4f}, {ratios[2]:.4f}")

    print("\n5. with dephasing (Eqs. 14-17)")
    worst = dict(prob=0.0, phi=0.0, q=0.0)
    for p in (0.005, 0.02, 0.1):
        for theta in np.linspace(0.0, np.pi / 2 - 0.05, 12):
            rot = {i: driver.rotated(i, float(theta), p) for i in range(4)}
            for s in (0, 1):
                ch = st.channel_from_states({i: st.branch(rot[i], s) for i in range(4)})
                worst["prob"] = max(worst["prob"], abs(ch.probability - st.prob_paper(theta, p, s == 0)))
                worst["phi"] = max(worst["phi"], st.angle_diff(ch.angle, st.angle_paper(theta, p, s == 0)))
                worst["q"] = max(worst["q"], abs(ch.dephasing - st.dephasing_paper(theta, p, s == 0)))
    check("p_s, phi_s and q_s from the Q# dumps match Eqs. 14-17 for p in {0.005, 0.02, 0.1}", max(worst.values()) < 1e-10,
          f"max |diff| prob {worst['prob']:.1e}, angle {worst['phi']:.1e}, dephasing {worst['q']:.1e}")
    qt = [st.exact_channel(0.0, p, 0).dephasing for p in (0.005, 0.01, 0.02)]
    qn = [st.exact_channel(0.0, p, 1).dephasing for p in (0.005, 0.01, 0.02)]
    check("theta = 0: the trivial branch dephases at third order in p (a weight-3 logical error), the nontrivial one at first order (about 3p)",
          abs(qt[1] / qt[0] - 8) < 0.5 and abs(qt[2] / qt[1] - 8) < 0.5 and abs(qn[0] / 0.005 - 3) < 0.1,
          f"q_t = {qt[0]:.2e}, {qt[1]:.2e}, {qt[2]:.2e} (ratios {qt[1] / qt[0]:.2f}, {qt[2] / qt[1]:.2f}); q_n / p = {qn[0] / 0.005:.3f}, {qn[1] / 0.01:.3f}, {qn[2] / 0.02:.3f}")
    odd = max(st.angle_diff(st.exact_channel(-th, 0.02, s).angle, -st.exact_channel(th, 0.02, s).angle) for th in (0.2, 0.5, 0.7) for s in (0, 1))
    check("odd symmetry phi_s(-theta) = -phi_s(theta)", odd < 1e-10, f"max |diff| = {odd:.1e}")

    print("\n6. shots against the exact channel")
    worst_sig = 0.0
    for theta, p, seed in ((0.15 * np.pi, 0.0, sd(7)), (0.1 * np.pi, 0.02, sd(8)), (0.25 * np.pi, 0.02, sd(9))):
        r = driver.ramsey(theta, p, 10000, seed)
        for name, s in (("t", 0), ("n", 1)):
            ch = st.exact_channel(theta, p, s)
            exact = (1 + (1 - 2 * ch.dephasing) * np.cos(ch.angle)) / 2
            sg = sigma(r[name]["p_plus"], r[name]["se"], exact)
            worst_sig = max(worst_sig, sg)
            print(f"      theta={theta / np.pi:.2f}pi p={p} {name}: P(X=+1|s) = {r[name]['p_plus']:.4f} +- {r[name]['se']:.4f}, exact {exact:.4f} ({sg:.1f} sigma)")
    check("Ramsey fringes within 3 sigma", worst_sig < 3, f"worst {worst_sig:.1f} sigma")
    theta, p = 0.15 * np.pi, 0.02
    tomo = driver.tomography(theta, p, 4000, sd(10))          # twelve runs, sd(10)..sd(21)
    worst_sig = 0.0
    for name, s in (("t", 0), ("n", 1)):
        ex = tomo["ex"][name]
        ch = st.exact_channel(theta, p, s)
        M, t = st.bloch_from_expectations(ex)
        phi, r = st.fit_rotation(M)
        Mx, _ = ch.bloch_map()
        px = ex[2]["x"], ex[2]["y"]
        se_phi = np.sqrt((px[1] * ex[2]["se_x"]) ** 2 + (px[0] * ex[2]["se_y"]) ** 2) / (px[0] ** 2 + px[1] ** 2)
        sg = st.angle_diff(np.arctan2(px[1], px[0]), ch.angle) / se_phi
        worst_sig = max(worst_sig, sg)
        print(f"      class {name}: fitted phi {phi / np.pi:+.4f} pi (exact {ch.angle / np.pi:+.4f}), residual infidelity {r:.4f} (exact {st.fit_rotation(Mx)[1]:.4f}), "
              f"|+> angle {np.arctan2(px[1], px[0]) / np.pi:+.4f} +- {se_phi / np.pi:.4f} pi ({sg:.1f} sigma), max |M - exact| {np.abs(M - Mx).max():.3f}, |t| {np.abs(t).max():.3f}")
    check("one-round tomography: the |+_L> angle within 3 sigma of the exact channel, both classes", worst_sig < 3, f"worst {worst_sig:.1f} sigma")
    theta, p = np.pi / 8, 0.02
    b = driver.two_round_bloch(theta, p, 8000, sd(22))          # two runs, sd(22), sd(23)
    worst_sig = 0.0
    for name, (s1, s2) in (("tt", (0, 0)), ("tn", (0, 1)), ("nt", (1, 0)), ("nn", (1, 1))):
        ch = st.exact_channel(theta, p, s1, second=(-theta, p, s2))
        prob = ch.probability * (7 if s1 else 1) * (7 if s2 else 1)
        sg = max(sigma(b[name]["x"], b[name]["se_x"], (1 - 2 * ch.dephasing) * np.cos(ch.angle)), sigma(b[name]["y"], b[name]["se_y"], (1 - 2 * ch.dephasing) * np.sin(ch.angle)),
                 sigma(b[name]["rate"], b[name]["se_rate"], prob))
        worst_sig = max(worst_sig, sg)
        print(f"      pair {name}: <X> {b[name]['x']:+.4f}, <Y> {b[name]['y']:+.4f}, rate {b[name]['rate']:.4f} (exact {(1 - 2 * ch.dephasing) * np.cos(ch.angle):+.4f}, "
              f"{(1 - 2 * ch.dephasing) * np.sin(ch.angle):+.4f}, {prob:.4f}; {sg:.1f} sigma)")
    check("two rounds from shots: <X_L>, <Y_L> and the pair probabilities within 3 sigma, all four pairs", worst_sig < 3, f"worst {worst_sig:.1f} sigma")

    print("\n7. two rounds exactly, from 21-qubit dumps")
    theta, p = 0.2 * np.pi, 0.02
    states = driver.two_rounds(theta, p, 40, sd(24))
    by_s1: dict[int, list[np.ndarray]] = {}
    for s1, rho in states:
        by_s1.setdefault(s1, []).append(rho)
    same = max(float(np.abs(r - rs[0]).max()) for rs in by_s1.values() for r in rs[1:]) if any(len(v) > 1 for v in by_s1.values()) else 0.0
    check("shots with the same first syndrome leave the same state (the branch is determined by the syndrome)", same < 1e-10,
          f"max |diff| = {same:.1e} over {len(states)} shots, syndromes {sorted(by_s1)}")
    worst = worst_sum = worst_prod = 0.0
    plus = np.array([[0.5, 0.5], [0.5, 0.5]])
    for s1, rhos in by_s1.items():
        first = st.exact_channel(theta, p, s1)
        for s2 in range(8):
            blk, _ = st.logical_block(st.branch(rhos[0], s2))
            ch = st.exact_channel(theta, p, s1, second=(-theta, p, s2))
            worst = max(worst, float(np.abs(blk - ch.apply(plus) / first.probability).max()))
            second = st.exact_channel(-theta, p, s2)
            worst_sum = max(worst_sum, st.angle_diff(ch.angle, first.angle + second.angle))
            worst_prod = max(worst_prod, abs(ch.probability - first.probability * second.probability))
    check("the Q# two-round branch for every (s1, s2) == E_{s2}(-theta) after E_{s1}(theta) in numpy", worst < 1e-10, f"max |diff| = {worst:.1e}")
    check("angles add and pair probabilities multiply across rounds", worst_sum < 1e-10 and worst_prod < 1e-12, f"max |diff| angle {worst_sum:.1e}, probability {worst_prod:.1e}")
    ch_tt = st.exact_channel(theta, p, 0, second=(-theta, p, 0))
    qt = st.exact_channel(theta, p, 0).dephasing
    check("trivial-trivial: total angle 0 and 1 - 2 q_tt = (1 - 2 q_t)^2", st.angle_diff(ch_tt.angle, 0) < 1e-10 and abs(ch_tt.dephasing - (1 - (1 - 2 * qt) ** 2) / 2) < 1e-12,
          f"phi_tt = {ch_tt.angle:.1e}, q_tt = {ch_tt.dephasing:.6f}, q_t = {qt:.6f}")

    print("\n8. seeds and random streams")
    a = driver.one_round(2, 0.3, 0.02, 1, 400, 5)
    b2 = driver.one_round(2, 0.3, 0.02, 1, 400, 5)
    c = driver.one_round(2, 0.3, 0.02, 1, 400, 6)
    d = driver.one_round(2, 0.3, 0.02, 1, 400, 5 + driver.SEED_STRIDE)
    shifted = bool((a[0][1:] == c[0][:-1]).all() and (a[1][1:] == c[1][:-1]).all())
    check("same seed -> same outcomes; seeds s and s+1 are the same stream shifted by one shot (the QDK seeds shot i with s + i)",
          bool((a[0] == b2[0]).all() and (a[1] == b2[1]).all()) and shifted and len(np.unique(a[0])) > 1, f"shifted copy: {shifted}")
    n = len(a[0])
    agree = max(float(((a[0][k:] == d[0][:n - k]) & (a[1][k:] == d[1][:n - k])).mean()) for k in (0, 1, 2, 3))
    check("seeds one SEED_STRIDE apart give neither the same stream nor a copy shifted by one to three shots", agree < 0.9,
          f"largest agreement over shifts 0..3: {agree:.2f} (1.00 for a shared stream)")
    sx, _ = driver.one_round(2, 0.3, 0.02, 1, 2000, sd(25))
    sy, _ = driver.one_round(2, 0.3, 0.02, 2, 2000, sd(26))
    check("the X and Y readout runs of a tomography point do not share their syndromes", float((sx == sy).mean()) < 0.9, f"syndrome agreement {float((sx == sy).mean()):.2f}")
    coins = driver.draw_and_measure(4000, sd(27))
    agree = [[float((coins[:, i] == coins[:, 2 + j]).mean()) for j in range(2)] for i in range(2)]
    info("under a seed the k-th DrawRandomDouble coin of a shot and its k-th measurement agree every time, the others at chance (two generators seeded alike)",
         f"coin 1 vs measurement 1, 2: {agree[0][0]:.3f}, {agree[0][1]:.3f}; coin 2 vs measurement 1, 2: {agree[1][0]:.3f}, {agree[1][1]:.3f}")
    syn, _ = driver.one_round(2, np.pi / 8, 0.02, 1, 20000, sd(28), variant="drawn")
    pt_drawn = float((syn == 0).mean())
    sg = sigma(pt_drawn, np.sqrt(exact_pt * (1 - exact_pt) / 20000), exact_pt)
    info("which is why noise sampled with DrawRandomBool under a seed biases the syndrome statistics (the measured dilation in group 2 does not)",
         f"trivial rate {pt_drawn:.4f} vs exact {exact_pt:.4f}: {sg:.1f} sigma")

    print()
    if failures:
        print(f"{len(failures)} check(s) FAILED: {', '.join(failures)}")
        return 1
    print("all checks passed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
